[gcp_service_account]
type = "service_account"
project_id = "ctqmanagervisitor"
private_key_id = "e35fd27207c93af0708b3c8fbcfb0f2fbb64b279"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDMBudHHArMgMtg
ZEQ09sMKWVkO1w2sBSaFcOwJq1zcuKzgSycr3F25S6IW9KsmRusmGvoUQQ3sA3a2
+3Z2KF3u9TRVz99/KLm9m6AULvEfWUbjKBc9infYARWNDc9ci6o/WnU+MluzFslA
DmWKYap+eqcwKSROgm8kyhk7TNE8gpsbKp/blQgiFnNN3w5DS/6MmgxKy2WA9Xop
AFTp0DXDJ34FfvfRIE0LcDoYOvFr8z3rvf7LR7z916rIoeiMhuoqNU02vJPOUT1g
KETI5uOuN9ok20qTP+nqaLmSNPqpNPrZO2yuMpdEmse0RmVVtr2wlHiCJLMuPEXm
g9Whmw9xAgMBAAECggEAAQ7FGquEy9AcHc0PRHYGB1L0wPyw67QgIb923cr3YYaM
kOIa2yGak8gWWEee7oUeGXW416uJqrBO6H5vvAeUCxXW1l4MQtC/e8Hnh8tBgT/Z
e/p8eltyKRrCVZedfFWWBZuOsYqZypki5HPep2O/ukWhAcEo2MZY1Kg+jr3kdMuX
Ka3mcpxeigsoV4KF+6EFZoyqrMddIZWB+2QrIjIgD3fK+xPcqV65paaQBbIavZg2
xnzwgrNICjbPXZ5PLJNmRUO7MYdBlceX2LpuD1r5+BZOqRmSkL+IrDDwnzt/myX5
78kYBllf3+aXgWBxuwzLY/K2cyMYIG1F4l2rMNJFgQKBgQD0+rAcLrcnLus5+4B7
RxTdig+37PZEw8zIwgpm/TApYBbXPy11STlYybTPrrLVaeUjA1yELeggm3MhFD31
eIfwn931NWR7aVE9Y1b+AR+1g0pgb68SmWCnX7pTxSSycHzR4Z6GAdk5bwJm04/1
NQ2nrjclnb46Q5jyPNzN5lFTUQKBgQDVNJZMSPpmAebuOQpgYuBELsHrS4f2ZOU0
liEMWtE1khSlXYM/q/eEpQkVcwsTwgrP+Jt/yKr3v8A3QDhnM/bNVllCVcYFJ0R5
DuGi3lr/Zy/5HkxOVtqcOfjyMrHXFi9WKwQVnwzoFOoD2EYWFtiZ4GErEfQeezJB
qZzQu+GyIQKBgQCPOPy7DUjA3LpjJLmh2RXGy4+S/TOhUkOoX2FLgtykY+wWnXYL
KusfEJXoEX+2K3nt9WoiUOB0J82wWjA7EeOP9zcBw9xiFlmLpUdXqvqJ2R8jsEfP
fOI4GExL62cf94nR/rD6MZx46oCh8zAnsIOyM7VEBawQTjLd9F029182cQKBgQC6
rBlwX3FGASJVsAGi1M+xQxMs1ewMUtjQSyZSb+2/LtD+3Lp+9C16qRkj+59WRE49
O1nC70qqMuy0M3lu+vN7Y8AxMXJ4rqHoMJxkgrU/6/P39YwwByHPKX8LaFGHlfgK
RQ2FdMXTKgSfKyxqSMSLLgdFs6l/SrR9A2m25Nm+oQKBgQDtn1sTU2DMd4znR9db
B0/zaSLXSKZoTDNENdcPS9fD0hBjwrGKfArSI+y6a6DwfdRcVu1LqVBtFlbTg/WI
WsOZDkaaiWl3mnL0y3LosQz4HZjOaE0Gz56d5iYkzyH/v4opzFdlnaCsuSP1s7Xa
1oX14y2m2TVIEn5a/Ngh4Udx4A==
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheet-access@ctqmanagervisitor.iam.gserviceaccount.com"
client_id = "100617113324947657060"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheet-access%40ctqmanagervisitor.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
